### ISSUE TITLE
data preprocess suggestion

### ISSUE THREAD

**Issue by kargaranamir** [laurieburchell/cs-lid-harder-than-you-think#1]
Hi Laurie, 

The code was super easy to use, thanks for that.

just some suggesstions.

I had troubles with this line of code: [reformat-itu-tureng.py#L38](https://github.com/laurieburchell/cs-lid-harder-than-you-think/blob/bc99723014814db3b3af43b6452d7aad57953b3d/data/scripts/tools/reformat-itu-tureng.py#L38)

The error is: ``f-string expression part cannot include a backslash``
I solve it this way (not very clean 😄):

```python
with open(args.out_file, 'w') as f:
    backslash_char = "\t"
    for s, t in zip(sents, tags):
        f.write(f"{s}{backslash_char}{'🍔'.join(t)}\n".replace("🍔", backslash_char))
```

- For turkish dataset there is no need to refer to the form ... 
you can access it here (TR-EN CS Corpus - with language tags.txt): 
```bash
https://github.com/zeynepyirmibes/code-switching-tr-en
```

- For indonasian also there is need to refer to email
you can access it here (825_Indonesian_English_CodeMixed.csv)
```bash
https://github.com/ir-nlp-csui/id-en-code-mixed
```

**Comment by laurieburchell** [comment]
Hi Amir,
Thanks for pointing out the bug! I put the join on a separate line, problem solved. 
I'll keep the emails in the script for now since this is how the authors ask people to obtain the data in the original papers.
